//User
export const ACTION_USER_SET = "ACTION_USER_SET";
export const ACTION_USER_SET_FIRSTNAME = "ACTION_USER_SET_FIRSTNAME";
export const ACTION_USER_SET_LASTNAME = "ACTION_USER_SET_LASTNAME";
export const ACTION_USER_SET_AGE = "ACTION_USER_SET_AGE";
export const ACTION_USER_SET_PHONE_NUMBER = "ACTION_USER_SET_PHONE_NUMBER";
export const ACTION_USER_SET_ID_CARD = "ACTION_USER_SET_ID_CARD";
export const ACTION_USER_SET_GENDER = "ACTION_USER_SET_GENDER";
export const ACTION_USER_SET_INTRODUCE = "ACTION_USER_SET_INTRODUCE";
export const ACTION_USER_SET_PROVINCE = "ACTION_USER_SET_PROVINCE";
export const ACTION_USER_SET_INTERESTED = "ACTION_USER_SET_INTERESTED";
export const ACTION_USER_SET_PHOTO_URL = "ACTION_USER_SET_PHOTO_URL";
export const ACTION_USER_SET_ROLE = "ACTION_USER_SET_ROLE";

//Job
export const ACTION_JOB_ACCEPT_SET = "ACTION_JOB_ACCEPT_SET";
export const ACTION_JOB_APPLY_SET = "ACTION_JOB_APPLY_SET";
export const ACTION_JOB_EMPLOYER_SET = "ACTION_JOB_EMPLOYER_SET";
export const ACTION_JOB_HISTORY_SET = "ACTION_JOB_HISTORY_SET";
export const ACTION_JOB_INVITE_SET = "ACTION_JOB_INVITE_SET";
export const ACTION_JOB_STATUS_SET = "ACTION_JOB_STATUS_SET";
