//User
export const ACTION_USER_SET = "ACTION_USER_SET";
export const ACTION_USER_SET_FIRSTNAME = "ACTION_USER_SET_FIRSTNAME";
export const ACTION_USER_SET_LASTNAME = "ACTION_USER_SET_LASTNAME";
export const ACTION_USER_SET_AGE = "ACTION_USER_SET_AGE";
export const ACTION_USER_SET_PHONE_NUMBER = "ACTION_USER_SET_PHONE_NUMBER";
export const ACTION_USER_SET_ID_CARD = "ACTION_USER_SET_ID_CARD";
export const ACTION_USER_SET_GENDER = "ACTION_USER_SET_GENDER";
export const ACTION_USER_SET_INTRODUCE = "ACTION_USER_SET_INTRODUCE";
export const ACTION_USER_SET_PROVINCE = "ACTION_USER_SET_PROVINCE";
export const ACTION_USER_SET_INTERESTED = "ACTION_USER_SET_INTERESTED";
export const ACTION_USER_SET_PHOTO_URL = "ACTION_USER_SET_PHOTO_URL";
export const ACTION_USER_SET_ROLE = "ACTION_USER_SET_ROLE";
export const ACTION_USER_SET_BANK = "ACTION_USER_SET_BANK";
export const ACTION_USER_SET_BKNK_ACCOUNT = "ACTION_USER_SET_BKNK_ACCOUNT";

//Job
export const ACTION_JOB_ACCEPT_SET = "ACTION_JOB_ACCEPT_SET";
export const ACTION_JOB_APPLY_SET = "ACTION_JOB_APPLY_SET";

export const ACTION_JOB_EMPLOYER_SET = "ACTION_JOB_EMPLOYER_SET";
export const ACTION_JOB_ACCEPT_EMPLOYEE_SET = "ACTION_JOB_ACCEPT_EMPLOYEE_SET";
export const ACTION_JOB_APPLY_EMPLOYEE_SET = "ACTION_JOB_APPLY_EMPLOYEE_SET";
export const ACTION_JOB_SELECT_EMPLOYEE_SET = "ACTION_JOB_SELECT_EMPLOYEE_SET";


export const ACTION_JOB_HISTORY_SET = "ACTION_JOB_HISTORY_SET";
export const ACTION_JOB_INVITE_SET = "ACTION_JOB_INVITE_SET";
export const ACTION_JOB_STATUS_SET = "ACTION_JOB_STATUS_SET";

//Employee Invite
export const ACTION_EMPLOYEE_INVITE_SET = "ACTION_EMPLOYEE_INVITE_SET";

//Page Status
export const ACTION_PAGE_STATUS_LOADING = "ACTION_PAGE_STATUS_LOADING";
export const ACTION_PAGE_STATUS_LOGIN = "ACTION_PAGE_STATUS_LOGIN";
export const ACTION_PAGE_STATUS_AVAILABLE = "ACTION_PAGE_STATUS_AVAILABLE";
